// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#ifndef PIGEON_PERMISSION_PLUS_API_G_H_
#define PIGEON_PERMISSION_PLUS_API_G_H_

#include <flutter_linux/flutter_linux.h>

G_BEGIN_DECLS

/**
 * permission_plus_linuxPermissionTypeMessage:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_CAMERA:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_MICROPHONE:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_PHOTOS:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_PHOTOS_ADD_ONLY:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_LOCATION:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_LOCATION_ALWAYS:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_LOCATION_WHEN_IN_USE:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_NOTIFICATION:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_CONTACTS:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_CONTACTS_READ_ONLY:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_CONTACTS_WRITE_ONLY:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_CALENDAR:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_CALENDAR_READ_ONLY:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_CALENDAR_WRITE_ONLY:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_REMINDERS:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_STORAGE:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_STORAGE_READ_ONLY:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_STORAGE_WRITE_ONLY:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_BLUETOOTH:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_SPEECH:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_MEDIA_LIBRARY:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_SENSORS:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_PHONE:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_SMS:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_APP_TRACKING_TRANSPARENCY:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_CRITICAL_ALERTS:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_VIDEOS:
 * PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_AUDIO:
 *
 * Mirror of `PermissionType` from `permission_plus_platform_interface`.
 */
typedef enum {
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_CAMERA = 0,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_MICROPHONE = 1,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_PHOTOS = 2,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_PHOTOS_ADD_ONLY = 3,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_LOCATION = 4,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_LOCATION_ALWAYS = 5,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_LOCATION_WHEN_IN_USE = 6,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_NOTIFICATION = 7,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_CONTACTS = 8,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_CONTACTS_READ_ONLY = 9,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_CONTACTS_WRITE_ONLY = 10,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_CALENDAR = 11,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_CALENDAR_READ_ONLY = 12,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_CALENDAR_WRITE_ONLY = 13,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_REMINDERS = 14,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_STORAGE = 15,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_STORAGE_READ_ONLY = 16,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_STORAGE_WRITE_ONLY = 17,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_BLUETOOTH = 18,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_SPEECH = 19,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_MEDIA_LIBRARY = 20,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_SENSORS = 21,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_PHONE = 22,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_SMS = 23,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_APP_TRACKING_TRANSPARENCY = 24,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_CRITICAL_ALERTS = 25,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_VIDEOS = 26,
  PERMISSION_PLUS_LINUX_PERMISSION_TYPE_MESSAGE_AUDIO = 27
} permission_plus_linuxPermissionTypeMessage;

/**
 * permission_plus_linuxPermissionStatusMessage:
 * PERMISSION_PLUS_LINUX_PERMISSION_STATUS_MESSAGE_NOT_DETERMINED:
 * PERMISSION_PLUS_LINUX_PERMISSION_STATUS_MESSAGE_GRANTED:
 * PERMISSION_PLUS_LINUX_PERMISSION_STATUS_MESSAGE_DENIED:
 * PERMISSION_PLUS_LINUX_PERMISSION_STATUS_MESSAGE_PERMANENTLY_DENIED:
 * PERMISSION_PLUS_LINUX_PERMISSION_STATUS_MESSAGE_RESTRICTED:
 * PERMISSION_PLUS_LINUX_PERMISSION_STATUS_MESSAGE_LIMITED:
 * PERMISSION_PLUS_LINUX_PERMISSION_STATUS_MESSAGE_PROVISIONAL:
 *
 * Mirror of `PermissionStatus` from `permission_plus_platform_interface`.
 */
typedef enum {
  PERMISSION_PLUS_LINUX_PERMISSION_STATUS_MESSAGE_NOT_DETERMINED = 0,
  PERMISSION_PLUS_LINUX_PERMISSION_STATUS_MESSAGE_GRANTED = 1,
  PERMISSION_PLUS_LINUX_PERMISSION_STATUS_MESSAGE_DENIED = 2,
  PERMISSION_PLUS_LINUX_PERMISSION_STATUS_MESSAGE_PERMANENTLY_DENIED = 3,
  PERMISSION_PLUS_LINUX_PERMISSION_STATUS_MESSAGE_RESTRICTED = 4,
  PERMISSION_PLUS_LINUX_PERMISSION_STATUS_MESSAGE_LIMITED = 5,
  PERMISSION_PLUS_LINUX_PERMISSION_STATUS_MESSAGE_PROVISIONAL = 6
} permission_plus_linuxPermissionStatusMessage;

/**
 * permission_plus_linuxLocationAccuracyMessage:
 * PERMISSION_PLUS_LINUX_LOCATION_ACCURACY_MESSAGE_REDUCED:
 * PERMISSION_PLUS_LINUX_LOCATION_ACCURACY_MESSAGE_PRECISE:
 *
 * Mirror of `LocationAccuracy` from `permission_plus_platform_interface`.
 */
typedef enum {
  PERMISSION_PLUS_LINUX_LOCATION_ACCURACY_MESSAGE_REDUCED = 0,
  PERMISSION_PLUS_LINUX_LOCATION_ACCURACY_MESSAGE_PRECISE = 1
} permission_plus_linuxLocationAccuracyMessage;

/**
 * permission_plus_linuxPermissionStatusMapEntry:
 *
 * Represents a single entry in a permission → status map.
 *
 * Used for returning results from [requestPermissions], since Pigeon
 * does not support `Map` with enum keys directly.
 */

G_DECLARE_FINAL_TYPE(permission_plus_linuxPermissionStatusMapEntry, permission_plus_linux_permission_status_map_entry, PERMISSION_PLUS_LINUX, PERMISSION_STATUS_MAP_ENTRY, GObject)

/**
 * permission_plus_linux_permission_status_map_entry_new:
 * permission: field in this object.
 * status: field in this object.
 *
 * Creates a new #PermissionStatusMapEntry object.
 *
 * Returns: a new #permission_plus_linuxPermissionStatusMapEntry
 */
permission_plus_linuxPermissionStatusMapEntry* permission_plus_linux_permission_status_map_entry_new(permission_plus_linuxPermissionTypeMessage permission, permission_plus_linuxPermissionStatusMessage status);

/**
 * permission_plus_linux_permission_status_map_entry_get_permission
 * @object: a #permission_plus_linuxPermissionStatusMapEntry.
 *
 * Gets the value of the permission field of @object.
 *
 * Returns: the field value.
 */
permission_plus_linuxPermissionTypeMessage permission_plus_linux_permission_status_map_entry_get_permission(permission_plus_linuxPermissionStatusMapEntry* object);

/**
 * permission_plus_linux_permission_status_map_entry_get_status
 * @object: a #permission_plus_linuxPermissionStatusMapEntry.
 *
 * Gets the value of the status field of @object.
 *
 * Returns: the field value.
 */
permission_plus_linuxPermissionStatusMessage permission_plus_linux_permission_status_map_entry_get_status(permission_plus_linuxPermissionStatusMapEntry* object);

/**
 * permission_plus_linux_permission_status_map_entry_equals:
 * @a: a #permission_plus_linuxPermissionStatusMapEntry.
 * @b: another #permission_plus_linuxPermissionStatusMapEntry.
 *
 * Checks if two #permission_plus_linuxPermissionStatusMapEntry objects are equal.
 *
 * Returns: TRUE if @a and @b are equal.
 */
gboolean permission_plus_linux_permission_status_map_entry_equals(permission_plus_linuxPermissionStatusMapEntry* a, permission_plus_linuxPermissionStatusMapEntry* b);

/**
 * permission_plus_linux_permission_status_map_entry_hash:
 * @object: a #permission_plus_linuxPermissionStatusMapEntry.
 *
 * Calculates a hash code for a #permission_plus_linuxPermissionStatusMapEntry object.
 *
 * Returns: the hash code.
 */
guint permission_plus_linux_permission_status_map_entry_hash(permission_plus_linuxPermissionStatusMapEntry* object);

G_DECLARE_FINAL_TYPE(permission_plus_linuxMessageCodec, permission_plus_linux_message_codec, PERMISSION_PLUS_LINUX, MESSAGE_CODEC, FlStandardMessageCodec)

/**
 * Custom type ID constants:
 *
 * Constants used to identify custom types in the codec.
 * They are used in the codec to encode and decode custom types.
 * They may be used in custom object creation functions to identify the type.
 */
extern const int permission_plus_linux_permission_type_message_type_id;
extern const int permission_plus_linux_permission_status_message_type_id;
extern const int permission_plus_linux_location_accuracy_message_type_id;
extern const int permission_plus_linux_permission_status_map_entry_type_id;

G_DECLARE_FINAL_TYPE(permission_plus_linuxPermissionPlusHostApi, permission_plus_linux_permission_plus_host_api, PERMISSION_PLUS_LINUX, PERMISSION_PLUS_HOST_API, GObject)

G_DECLARE_FINAL_TYPE(permission_plus_linuxPermissionPlusHostApiResponseHandle, permission_plus_linux_permission_plus_host_api_response_handle, PERMISSION_PLUS_LINUX, PERMISSION_PLUS_HOST_API_RESPONSE_HANDLE, GObject)

/**
 * permission_plus_linuxPermissionPlusHostApiVTable:
 *
 * Table of functions exposed by PermissionPlusHostApi to be implemented by the API provider.
 */
typedef struct {
  void (*check_permission)(permission_plus_linuxPermissionTypeMessage permission, permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, gpointer user_data);
  void (*request_permission)(permission_plus_linuxPermissionTypeMessage permission, permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, gpointer user_data);
  void (*request_permissions)(FlValue* permissions, permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, gpointer user_data);
  void (*open_settings)(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, gpointer user_data);
  void (*should_show_rationale)(permission_plus_linuxPermissionTypeMessage permission, permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, gpointer user_data);
  void (*get_location_accuracy)(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, gpointer user_data);
  void (*request_temporary_precise_location)(const gchar* purpose_key, permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, gpointer user_data);
} permission_plus_linuxPermissionPlusHostApiVTable;

/**
 * permission_plus_linux_permission_plus_host_api_set_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 * @vtable: implementations of the methods in this API.
 * @user_data: (closure): user data to pass to the functions in @vtable.
 * @user_data_free_func: (allow-none): a function which gets called to free @user_data, or %NULL.
 *
 * Connects the method handlers in the PermissionPlusHostApi API.
 */
void permission_plus_linux_permission_plus_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const permission_plus_linuxPermissionPlusHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func);

/**
 * permission_plus_linux_permission_plus_host_api_clear_method_handlers:
 *
 * @messenger: an #FlBinaryMessenger.
 * @suffix: (allow-none): a suffix to add to the API or %NULL for none.
 *
 * Clears the method handlers in the PermissionPlusHostApi API.
 */
void permission_plus_linux_permission_plus_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix);

/**
 * permission_plus_linux_permission_plus_host_api_respond_check_permission:
 * @response_handle: a #permission_plus_linuxPermissionPlusHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to PermissionPlusHostApi.checkPermission. 
 */
void permission_plus_linux_permission_plus_host_api_respond_check_permission(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, permission_plus_linuxPermissionStatusMessage return_value);

/**
 * permission_plus_linux_permission_plus_host_api_respond_error_check_permission:
 * @response_handle: a #permission_plus_linuxPermissionPlusHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to PermissionPlusHostApi.checkPermission. 
 */
void permission_plus_linux_permission_plus_host_api_respond_error_check_permission(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * permission_plus_linux_permission_plus_host_api_respond_request_permission:
 * @response_handle: a #permission_plus_linuxPermissionPlusHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to PermissionPlusHostApi.requestPermission. 
 */
void permission_plus_linux_permission_plus_host_api_respond_request_permission(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, permission_plus_linuxPermissionStatusMessage return_value);

/**
 * permission_plus_linux_permission_plus_host_api_respond_error_request_permission:
 * @response_handle: a #permission_plus_linuxPermissionPlusHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to PermissionPlusHostApi.requestPermission. 
 */
void permission_plus_linux_permission_plus_host_api_respond_error_request_permission(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * permission_plus_linux_permission_plus_host_api_respond_request_permissions:
 * @response_handle: a #permission_plus_linuxPermissionPlusHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to PermissionPlusHostApi.requestPermissions. 
 */
void permission_plus_linux_permission_plus_host_api_respond_request_permissions(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, FlValue* return_value);

/**
 * permission_plus_linux_permission_plus_host_api_respond_error_request_permissions:
 * @response_handle: a #permission_plus_linuxPermissionPlusHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to PermissionPlusHostApi.requestPermissions. 
 */
void permission_plus_linux_permission_plus_host_api_respond_error_request_permissions(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * permission_plus_linux_permission_plus_host_api_respond_open_settings:
 * @response_handle: a #permission_plus_linuxPermissionPlusHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to PermissionPlusHostApi.openSettings. 
 */
void permission_plus_linux_permission_plus_host_api_respond_open_settings(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, gboolean return_value);

/**
 * permission_plus_linux_permission_plus_host_api_respond_error_open_settings:
 * @response_handle: a #permission_plus_linuxPermissionPlusHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to PermissionPlusHostApi.openSettings. 
 */
void permission_plus_linux_permission_plus_host_api_respond_error_open_settings(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * permission_plus_linux_permission_plus_host_api_respond_should_show_rationale:
 * @response_handle: a #permission_plus_linuxPermissionPlusHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to PermissionPlusHostApi.shouldShowRationale. 
 */
void permission_plus_linux_permission_plus_host_api_respond_should_show_rationale(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, gboolean return_value);

/**
 * permission_plus_linux_permission_plus_host_api_respond_error_should_show_rationale:
 * @response_handle: a #permission_plus_linuxPermissionPlusHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to PermissionPlusHostApi.shouldShowRationale. 
 */
void permission_plus_linux_permission_plus_host_api_respond_error_should_show_rationale(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * permission_plus_linux_permission_plus_host_api_respond_get_location_accuracy:
 * @response_handle: a #permission_plus_linuxPermissionPlusHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to PermissionPlusHostApi.getLocationAccuracy. 
 */
void permission_plus_linux_permission_plus_host_api_respond_get_location_accuracy(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, permission_plus_linuxLocationAccuracyMessage return_value);

/**
 * permission_plus_linux_permission_plus_host_api_respond_error_get_location_accuracy:
 * @response_handle: a #permission_plus_linuxPermissionPlusHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to PermissionPlusHostApi.getLocationAccuracy. 
 */
void permission_plus_linux_permission_plus_host_api_respond_error_get_location_accuracy(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

/**
 * permission_plus_linux_permission_plus_host_api_respond_request_temporary_precise_location:
 * @response_handle: a #permission_plus_linuxPermissionPlusHostApiResponseHandle.
 * @return_value: location to write the value returned by this method.
 *
 * Responds to PermissionPlusHostApi.requestTemporaryPreciseLocation. 
 */
void permission_plus_linux_permission_plus_host_api_respond_request_temporary_precise_location(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, permission_plus_linuxPermissionStatusMessage return_value);

/**
 * permission_plus_linux_permission_plus_host_api_respond_error_request_temporary_precise_location:
 * @response_handle: a #permission_plus_linuxPermissionPlusHostApiResponseHandle.
 * @code: error code.
 * @message: error message.
 * @details: (allow-none): error details or %NULL.
 *
 * Responds with an error to PermissionPlusHostApi.requestTemporaryPreciseLocation. 
 */
void permission_plus_linux_permission_plus_host_api_respond_error_request_temporary_precise_location(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details);

G_END_DECLS

#endif  // PIGEON_PERMISSION_PLUS_API_G_H_
