// Autogenerated from Pigeon (v26.3.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#include <cmath>

#include <string.h>
#include "permission_plus_api.g.h"
static guint G_GNUC_UNUSED flpigeon_hash_double(double v) {
  if (std::isnan(v)) {
    return static_cast<guint>(0x7FF80000);
  }
  if (v == 0.0) {
    v = 0.0;
  }
  union { double d; uint64_t u; } u;
  u.d = v;
  return static_cast<guint>(u.u ^ (u.u >> 32));
}
static gboolean G_GNUC_UNUSED flpigeon_equals_double(double a, double b) {
  return (a == b) || (std::isnan(a) && std::isnan(b));
}
static gboolean G_GNUC_UNUSED flpigeon_deep_equals(FlValue* a, FlValue* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (fl_value_get_type(a) != fl_value_get_type(b)) {
    return FALSE;
  }
  switch (fl_value_get_type(a)) {
    case FL_VALUE_TYPE_NULL:
      return TRUE;
    case FL_VALUE_TYPE_BOOL:
      return fl_value_get_bool(a) == fl_value_get_bool(b);
    case FL_VALUE_TYPE_INT:
      return fl_value_get_int(a) == fl_value_get_int(b);
    case FL_VALUE_TYPE_FLOAT: {
      return flpigeon_equals_double(fl_value_get_float(a), fl_value_get_float(b));
    }
    case FL_VALUE_TYPE_STRING:
      return g_strcmp0(fl_value_get_string(a), fl_value_get_string(b)) == 0;
    case FL_VALUE_TYPE_UINT8_LIST:
      return fl_value_get_length(a) == fl_value_get_length(b) &&
             memcmp(fl_value_get_uint8_list(a), fl_value_get_uint8_list(b), fl_value_get_length(a)) == 0;
    case FL_VALUE_TYPE_INT32_LIST:
      return fl_value_get_length(a) == fl_value_get_length(b) &&
             memcmp(fl_value_get_int32_list(a), fl_value_get_int32_list(b), fl_value_get_length(a) * sizeof(int32_t)) == 0;
    case FL_VALUE_TYPE_INT64_LIST:
      return fl_value_get_length(a) == fl_value_get_length(b) &&
             memcmp(fl_value_get_int64_list(a), fl_value_get_int64_list(b), fl_value_get_length(a) * sizeof(int64_t)) == 0;
    case FL_VALUE_TYPE_FLOAT_LIST: {
      size_t len = fl_value_get_length(a);
      if (len != fl_value_get_length(b)) {
        return FALSE;
      }
      const double* a_data = fl_value_get_float_list(a);
      const double* b_data = fl_value_get_float_list(b);
      for (size_t i = 0; i < len; i++) {
      if (!flpigeon_equals_double(a_data[i], b_data[i])) {
        return FALSE;
      }
    }
      return TRUE;
    }
    case FL_VALUE_TYPE_LIST: {
      size_t len = fl_value_get_length(a);
      if (len != fl_value_get_length(b)) {
        return FALSE;
      }
      for (size_t i = 0; i < len; i++) {
      if (!flpigeon_deep_equals(fl_value_get_list_value(a, i), fl_value_get_list_value(b, i))) {
        return FALSE;
      }
    }
      return TRUE;
    }
    case FL_VALUE_TYPE_MAP: {
      size_t len = fl_value_get_length(a);
      if (len != fl_value_get_length(b)) {
        return FALSE;
      }
      for (size_t i = 0; i < len; i++) {
      FlValue* key = fl_value_get_map_key(a, i);
      FlValue* val = fl_value_get_map_value(a, i);
      gboolean found = FALSE;
      for (size_t j = 0; j < len; j++) {
        FlValue* b_key = fl_value_get_map_key(b, j);
        if (flpigeon_deep_equals(key, b_key)) {
          FlValue* b_val = fl_value_get_map_value(b, j);
          if (flpigeon_deep_equals(val, b_val)) {
            found = TRUE;
            break;
          } else {
            return FALSE;
          }
        }
      }
      if (!found) {
        return FALSE;
      }
    }
      return TRUE;
    }
    default:
      return FALSE;
  }
  return FALSE;
}
static guint G_GNUC_UNUSED flpigeon_deep_hash(FlValue* value) {
  if (value == nullptr) {
    return 0;
  }
  switch (fl_value_get_type(value)) {
    case FL_VALUE_TYPE_NULL:
      return 0;
    case FL_VALUE_TYPE_BOOL:
      return fl_value_get_bool(value) ? 1231 : 1237;
    case FL_VALUE_TYPE_INT: {
      int64_t v = fl_value_get_int(value);
      return static_cast<guint>(v ^ (v >> 32));
    }
    case FL_VALUE_TYPE_FLOAT:
      return flpigeon_hash_double(fl_value_get_float(value));
    case FL_VALUE_TYPE_STRING:
      return g_str_hash(fl_value_get_string(value));
    case FL_VALUE_TYPE_UINT8_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const uint8_t* data = fl_value_get_uint8_list(value);
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + data[i];
      }
      return result;
    }
    case FL_VALUE_TYPE_INT32_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const int32_t* data = fl_value_get_int32_list(value);
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + static_cast<guint>(data[i]);
      }
      return result;
    }
    case FL_VALUE_TYPE_INT64_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const int64_t* data = fl_value_get_int64_list(value);
      for (size_t i = 0; i < len; i++) {
        result = result * 31 + static_cast<guint>(data[i] ^ (data[i] >> 32));
      }
      return result;
    }
    case FL_VALUE_TYPE_FLOAT_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      const double* data = fl_value_get_float_list(value);
      for (size_t i = 0; i < len; i++) {
      result = result * 31 + flpigeon_hash_double(data[i]);
    }
      return result;
    }
    case FL_VALUE_TYPE_LIST: {
      guint result = 1;
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
      result = result * 31 + flpigeon_deep_hash(fl_value_get_list_value(value, i));
    }
      return result;
    }
    case FL_VALUE_TYPE_MAP: {
      guint result = 0;
      size_t len = fl_value_get_length(value);
      for (size_t i = 0; i < len; i++) {
      result += ((flpigeon_deep_hash(fl_value_get_map_key(value, i)) * 31) ^ flpigeon_deep_hash(fl_value_get_map_value(value, i)));
    }
      return result;
    }
    default:
      return static_cast<guint>(fl_value_get_type(value));
  }
  return 0;
}

struct _permission_plus_linuxPermissionStatusMapEntry {
  GObject parent_instance;

  permission_plus_linuxPermissionTypeMessage permission;
  permission_plus_linuxPermissionStatusMessage status;
};

G_DEFINE_TYPE(permission_plus_linuxPermissionStatusMapEntry, permission_plus_linux_permission_status_map_entry, G_TYPE_OBJECT)

static void permission_plus_linux_permission_status_map_entry_dispose(GObject* object) {
  G_OBJECT_CLASS(permission_plus_linux_permission_status_map_entry_parent_class)->dispose(object);
}

static void permission_plus_linux_permission_status_map_entry_init(permission_plus_linuxPermissionStatusMapEntry* self) {
}

static void permission_plus_linux_permission_status_map_entry_class_init(permission_plus_linuxPermissionStatusMapEntryClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = permission_plus_linux_permission_status_map_entry_dispose;
}

permission_plus_linuxPermissionStatusMapEntry* permission_plus_linux_permission_status_map_entry_new(permission_plus_linuxPermissionTypeMessage permission, permission_plus_linuxPermissionStatusMessage status) {
  permission_plus_linuxPermissionStatusMapEntry* self = PERMISSION_PLUS_LINUX_PERMISSION_STATUS_MAP_ENTRY(g_object_new(permission_plus_linux_permission_status_map_entry_get_type(), nullptr));
  self->permission = permission;
  self->status = status;
  return self;
}

permission_plus_linuxPermissionTypeMessage permission_plus_linux_permission_status_map_entry_get_permission(permission_plus_linuxPermissionStatusMapEntry* self) {
  g_return_val_if_fail(PERMISSION_PLUS_LINUX_IS_PERMISSION_STATUS_MAP_ENTRY(self), static_cast<permission_plus_linuxPermissionTypeMessage>(0));
  return self->permission;
}

permission_plus_linuxPermissionStatusMessage permission_plus_linux_permission_status_map_entry_get_status(permission_plus_linuxPermissionStatusMapEntry* self) {
  g_return_val_if_fail(PERMISSION_PLUS_LINUX_IS_PERMISSION_STATUS_MAP_ENTRY(self), static_cast<permission_plus_linuxPermissionStatusMessage>(0));
  return self->status;
}

static FlValue* permission_plus_linux_permission_status_map_entry_to_list(permission_plus_linuxPermissionStatusMapEntry* self) {
  FlValue* values = fl_value_new_list();
  fl_value_append_take(values, fl_value_new_custom(permission_plus_linux_permission_type_message_type_id, fl_value_new_int(self->permission), (GDestroyNotify)fl_value_unref));
  fl_value_append_take(values, fl_value_new_custom(permission_plus_linux_permission_status_message_type_id, fl_value_new_int(self->status), (GDestroyNotify)fl_value_unref));
  return values;
}

static permission_plus_linuxPermissionStatusMapEntry* permission_plus_linux_permission_status_map_entry_new_from_list(FlValue* values) {
  FlValue* value0 = fl_value_get_list_value(values, 0);
  permission_plus_linuxPermissionTypeMessage permission = static_cast<permission_plus_linuxPermissionTypeMessage>(fl_value_get_int(reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value0)))));
  FlValue* value1 = fl_value_get_list_value(values, 1);
  permission_plus_linuxPermissionStatusMessage status = static_cast<permission_plus_linuxPermissionStatusMessage>(fl_value_get_int(reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value1)))));
  return permission_plus_linux_permission_status_map_entry_new(permission, status);
}

gboolean permission_plus_linux_permission_status_map_entry_equals(permission_plus_linuxPermissionStatusMapEntry* a, permission_plus_linuxPermissionStatusMapEntry* b) {
  if (a == b) {
    return TRUE;
  }
  if (a == nullptr || b == nullptr) {
    return FALSE;
  }
  if (a->permission != b->permission) {
    return FALSE;
  }
  if (a->status != b->status) {
    return FALSE;
  }
  return TRUE;
}

guint permission_plus_linux_permission_status_map_entry_hash(permission_plus_linuxPermissionStatusMapEntry* self) {
  g_return_val_if_fail(PERMISSION_PLUS_LINUX_IS_PERMISSION_STATUS_MAP_ENTRY(self), 0);
  guint result = 0;
  result = result * 31 + static_cast<guint>(self->permission);
  result = result * 31 + static_cast<guint>(self->status);
  return result;
}

struct _permission_plus_linuxMessageCodec {
  FlStandardMessageCodec parent_instance;

};

G_DEFINE_TYPE(permission_plus_linuxMessageCodec, permission_plus_linux_message_codec, fl_standard_message_codec_get_type())

const int permission_plus_linux_permission_type_message_type_id = 129;
const int permission_plus_linux_permission_status_message_type_id = 130;
const int permission_plus_linux_location_accuracy_message_type_id = 131;
const int permission_plus_linux_permission_status_map_entry_type_id = 132;

static gboolean permission_plus_linux_message_codec_write_permission_plus_linux_permission_type_message(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  uint8_t type = permission_plus_linux_permission_type_message_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  return fl_standard_message_codec_write_value(codec, buffer, value, error);
}

static gboolean permission_plus_linux_message_codec_write_permission_plus_linux_permission_status_message(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  uint8_t type = permission_plus_linux_permission_status_message_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  return fl_standard_message_codec_write_value(codec, buffer, value, error);
}

static gboolean permission_plus_linux_message_codec_write_permission_plus_linux_location_accuracy_message(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  uint8_t type = permission_plus_linux_location_accuracy_message_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  return fl_standard_message_codec_write_value(codec, buffer, value, error);
}

static gboolean permission_plus_linux_message_codec_write_permission_plus_linux_permission_status_map_entry(FlStandardMessageCodec* codec, GByteArray* buffer, permission_plus_linuxPermissionStatusMapEntry* value, GError** error) {
  uint8_t type = permission_plus_linux_permission_status_map_entry_type_id;
  g_byte_array_append(buffer, &type, sizeof(uint8_t));
  g_autoptr(FlValue) values = permission_plus_linux_permission_status_map_entry_to_list(value);
  return fl_standard_message_codec_write_value(codec, buffer, values, error);
}

static gboolean permission_plus_linux_message_codec_write_value(FlStandardMessageCodec* codec, GByteArray* buffer, FlValue* value, GError** error) {
  if (fl_value_get_type(value) == FL_VALUE_TYPE_CUSTOM) {
    switch (fl_value_get_custom_type(value)) {
      case permission_plus_linux_permission_type_message_type_id:
        return permission_plus_linux_message_codec_write_permission_plus_linux_permission_type_message(codec, buffer, reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value))), error);
      case permission_plus_linux_permission_status_message_type_id:
        return permission_plus_linux_message_codec_write_permission_plus_linux_permission_status_message(codec, buffer, reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value))), error);
      case permission_plus_linux_location_accuracy_message_type_id:
        return permission_plus_linux_message_codec_write_permission_plus_linux_location_accuracy_message(codec, buffer, reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value))), error);
      case permission_plus_linux_permission_status_map_entry_type_id:
        return permission_plus_linux_message_codec_write_permission_plus_linux_permission_status_map_entry(codec, buffer, PERMISSION_PLUS_LINUX_PERMISSION_STATUS_MAP_ENTRY(fl_value_get_custom_value_object(value)), error);
    }
  }

  return FL_STANDARD_MESSAGE_CODEC_CLASS(permission_plus_linux_message_codec_parent_class)->write_value(codec, buffer, value, error);
}

static FlValue* permission_plus_linux_message_codec_read_permission_plus_linux_permission_type_message(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  return fl_value_new_custom(permission_plus_linux_permission_type_message_type_id, fl_standard_message_codec_read_value(codec, buffer, offset, error), (GDestroyNotify)fl_value_unref);
}

static FlValue* permission_plus_linux_message_codec_read_permission_plus_linux_permission_status_message(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  return fl_value_new_custom(permission_plus_linux_permission_status_message_type_id, fl_standard_message_codec_read_value(codec, buffer, offset, error), (GDestroyNotify)fl_value_unref);
}

static FlValue* permission_plus_linux_message_codec_read_permission_plus_linux_location_accuracy_message(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  return fl_value_new_custom(permission_plus_linux_location_accuracy_message_type_id, fl_standard_message_codec_read_value(codec, buffer, offset, error), (GDestroyNotify)fl_value_unref);
}

static FlValue* permission_plus_linux_message_codec_read_permission_plus_linux_permission_status_map_entry(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, GError** error) {
  g_autoptr(FlValue) values = fl_standard_message_codec_read_value(codec, buffer, offset, error);
  if (values == nullptr) {
    return nullptr;
  }

  g_autoptr(permission_plus_linuxPermissionStatusMapEntry) value = permission_plus_linux_permission_status_map_entry_new_from_list(values);
  if (value == nullptr) {
    g_set_error(error, FL_MESSAGE_CODEC_ERROR, FL_MESSAGE_CODEC_ERROR_FAILED, "Invalid data received for MessageData");
    return nullptr;
  }

  return fl_value_new_custom_object(permission_plus_linux_permission_status_map_entry_type_id, G_OBJECT(value));
}

static FlValue* permission_plus_linux_message_codec_read_value_of_type(FlStandardMessageCodec* codec, GBytes* buffer, size_t* offset, int type, GError** error) {
  switch (type) {
    case permission_plus_linux_permission_type_message_type_id:
      return permission_plus_linux_message_codec_read_permission_plus_linux_permission_type_message(codec, buffer, offset, error);
    case permission_plus_linux_permission_status_message_type_id:
      return permission_plus_linux_message_codec_read_permission_plus_linux_permission_status_message(codec, buffer, offset, error);
    case permission_plus_linux_location_accuracy_message_type_id:
      return permission_plus_linux_message_codec_read_permission_plus_linux_location_accuracy_message(codec, buffer, offset, error);
    case permission_plus_linux_permission_status_map_entry_type_id:
      return permission_plus_linux_message_codec_read_permission_plus_linux_permission_status_map_entry(codec, buffer, offset, error);
    default:
      return FL_STANDARD_MESSAGE_CODEC_CLASS(permission_plus_linux_message_codec_parent_class)->read_value_of_type(codec, buffer, offset, type, error);
  }
}

static void permission_plus_linux_message_codec_init(permission_plus_linuxMessageCodec* self) {
}

static void permission_plus_linux_message_codec_class_init(permission_plus_linuxMessageCodecClass* klass) {
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->write_value = permission_plus_linux_message_codec_write_value;
  FL_STANDARD_MESSAGE_CODEC_CLASS(klass)->read_value_of_type = permission_plus_linux_message_codec_read_value_of_type;
}

static permission_plus_linuxMessageCodec* permission_plus_linux_message_codec_new() {
  permission_plus_linuxMessageCodec* self = PERMISSION_PLUS_LINUX_MESSAGE_CODEC(g_object_new(permission_plus_linux_message_codec_get_type(), nullptr));
  return self;
}

struct _permission_plus_linuxPermissionPlusHostApiResponseHandle {
  GObject parent_instance;

  FlBasicMessageChannel* channel;
  FlBasicMessageChannelResponseHandle* response_handle;
};

G_DEFINE_TYPE(permission_plus_linuxPermissionPlusHostApiResponseHandle, permission_plus_linux_permission_plus_host_api_response_handle, G_TYPE_OBJECT)

static void permission_plus_linux_permission_plus_host_api_response_handle_dispose(GObject* object) {
  permission_plus_linuxPermissionPlusHostApiResponseHandle* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_RESPONSE_HANDLE(object);
  g_clear_object(&self->channel);
  g_clear_object(&self->response_handle);
  G_OBJECT_CLASS(permission_plus_linux_permission_plus_host_api_response_handle_parent_class)->dispose(object);
}

static void permission_plus_linux_permission_plus_host_api_response_handle_init(permission_plus_linuxPermissionPlusHostApiResponseHandle* self) {
}

static void permission_plus_linux_permission_plus_host_api_response_handle_class_init(permission_plus_linuxPermissionPlusHostApiResponseHandleClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = permission_plus_linux_permission_plus_host_api_response_handle_dispose;
}

static permission_plus_linuxPermissionPlusHostApiResponseHandle* permission_plus_linux_permission_plus_host_api_response_handle_new(FlBasicMessageChannel* channel, FlBasicMessageChannelResponseHandle* response_handle) {
  permission_plus_linuxPermissionPlusHostApiResponseHandle* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_RESPONSE_HANDLE(g_object_new(permission_plus_linux_permission_plus_host_api_response_handle_get_type(), nullptr));
  self->channel = FL_BASIC_MESSAGE_CHANNEL(g_object_ref(channel));
  self->response_handle = FL_BASIC_MESSAGE_CHANNEL_RESPONSE_HANDLE(g_object_ref(response_handle));
  return self;
}

G_DECLARE_FINAL_TYPE(permission_plus_linuxPermissionPlusHostApiCheckPermissionResponse, permission_plus_linux_permission_plus_host_api_check_permission_response, PERMISSION_PLUS_LINUX, PERMISSION_PLUS_HOST_API_CHECK_PERMISSION_RESPONSE, GObject)

struct _permission_plus_linuxPermissionPlusHostApiCheckPermissionResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(permission_plus_linuxPermissionPlusHostApiCheckPermissionResponse, permission_plus_linux_permission_plus_host_api_check_permission_response, G_TYPE_OBJECT)

static void permission_plus_linux_permission_plus_host_api_check_permission_response_dispose(GObject* object) {
  permission_plus_linuxPermissionPlusHostApiCheckPermissionResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_CHECK_PERMISSION_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(permission_plus_linux_permission_plus_host_api_check_permission_response_parent_class)->dispose(object);
}

static void permission_plus_linux_permission_plus_host_api_check_permission_response_init(permission_plus_linuxPermissionPlusHostApiCheckPermissionResponse* self) {
}

static void permission_plus_linux_permission_plus_host_api_check_permission_response_class_init(permission_plus_linuxPermissionPlusHostApiCheckPermissionResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = permission_plus_linux_permission_plus_host_api_check_permission_response_dispose;
}

static permission_plus_linuxPermissionPlusHostApiCheckPermissionResponse* permission_plus_linux_permission_plus_host_api_check_permission_response_new(permission_plus_linuxPermissionStatusMessage return_value) {
  permission_plus_linuxPermissionPlusHostApiCheckPermissionResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_CHECK_PERMISSION_RESPONSE(g_object_new(permission_plus_linux_permission_plus_host_api_check_permission_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_custom(permission_plus_linux_permission_status_message_type_id, fl_value_new_int(return_value), (GDestroyNotify)fl_value_unref));
  return self;
}

static permission_plus_linuxPermissionPlusHostApiCheckPermissionResponse* permission_plus_linux_permission_plus_host_api_check_permission_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  permission_plus_linuxPermissionPlusHostApiCheckPermissionResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_CHECK_PERMISSION_RESPONSE(g_object_new(permission_plus_linux_permission_plus_host_api_check_permission_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

G_DECLARE_FINAL_TYPE(permission_plus_linuxPermissionPlusHostApiRequestPermissionResponse, permission_plus_linux_permission_plus_host_api_request_permission_response, PERMISSION_PLUS_LINUX, PERMISSION_PLUS_HOST_API_REQUEST_PERMISSION_RESPONSE, GObject)

struct _permission_plus_linuxPermissionPlusHostApiRequestPermissionResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(permission_plus_linuxPermissionPlusHostApiRequestPermissionResponse, permission_plus_linux_permission_plus_host_api_request_permission_response, G_TYPE_OBJECT)

static void permission_plus_linux_permission_plus_host_api_request_permission_response_dispose(GObject* object) {
  permission_plus_linuxPermissionPlusHostApiRequestPermissionResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_REQUEST_PERMISSION_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(permission_plus_linux_permission_plus_host_api_request_permission_response_parent_class)->dispose(object);
}

static void permission_plus_linux_permission_plus_host_api_request_permission_response_init(permission_plus_linuxPermissionPlusHostApiRequestPermissionResponse* self) {
}

static void permission_plus_linux_permission_plus_host_api_request_permission_response_class_init(permission_plus_linuxPermissionPlusHostApiRequestPermissionResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = permission_plus_linux_permission_plus_host_api_request_permission_response_dispose;
}

static permission_plus_linuxPermissionPlusHostApiRequestPermissionResponse* permission_plus_linux_permission_plus_host_api_request_permission_response_new(permission_plus_linuxPermissionStatusMessage return_value) {
  permission_plus_linuxPermissionPlusHostApiRequestPermissionResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_REQUEST_PERMISSION_RESPONSE(g_object_new(permission_plus_linux_permission_plus_host_api_request_permission_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_custom(permission_plus_linux_permission_status_message_type_id, fl_value_new_int(return_value), (GDestroyNotify)fl_value_unref));
  return self;
}

static permission_plus_linuxPermissionPlusHostApiRequestPermissionResponse* permission_plus_linux_permission_plus_host_api_request_permission_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  permission_plus_linuxPermissionPlusHostApiRequestPermissionResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_REQUEST_PERMISSION_RESPONSE(g_object_new(permission_plus_linux_permission_plus_host_api_request_permission_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

G_DECLARE_FINAL_TYPE(permission_plus_linuxPermissionPlusHostApiRequestPermissionsResponse, permission_plus_linux_permission_plus_host_api_request_permissions_response, PERMISSION_PLUS_LINUX, PERMISSION_PLUS_HOST_API_REQUEST_PERMISSIONS_RESPONSE, GObject)

struct _permission_plus_linuxPermissionPlusHostApiRequestPermissionsResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(permission_plus_linuxPermissionPlusHostApiRequestPermissionsResponse, permission_plus_linux_permission_plus_host_api_request_permissions_response, G_TYPE_OBJECT)

static void permission_plus_linux_permission_plus_host_api_request_permissions_response_dispose(GObject* object) {
  permission_plus_linuxPermissionPlusHostApiRequestPermissionsResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_REQUEST_PERMISSIONS_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(permission_plus_linux_permission_plus_host_api_request_permissions_response_parent_class)->dispose(object);
}

static void permission_plus_linux_permission_plus_host_api_request_permissions_response_init(permission_plus_linuxPermissionPlusHostApiRequestPermissionsResponse* self) {
}

static void permission_plus_linux_permission_plus_host_api_request_permissions_response_class_init(permission_plus_linuxPermissionPlusHostApiRequestPermissionsResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = permission_plus_linux_permission_plus_host_api_request_permissions_response_dispose;
}

static permission_plus_linuxPermissionPlusHostApiRequestPermissionsResponse* permission_plus_linux_permission_plus_host_api_request_permissions_response_new(FlValue* return_value) {
  permission_plus_linuxPermissionPlusHostApiRequestPermissionsResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_REQUEST_PERMISSIONS_RESPONSE(g_object_new(permission_plus_linux_permission_plus_host_api_request_permissions_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_ref(return_value));
  return self;
}

static permission_plus_linuxPermissionPlusHostApiRequestPermissionsResponse* permission_plus_linux_permission_plus_host_api_request_permissions_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  permission_plus_linuxPermissionPlusHostApiRequestPermissionsResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_REQUEST_PERMISSIONS_RESPONSE(g_object_new(permission_plus_linux_permission_plus_host_api_request_permissions_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

G_DECLARE_FINAL_TYPE(permission_plus_linuxPermissionPlusHostApiOpenSettingsResponse, permission_plus_linux_permission_plus_host_api_open_settings_response, PERMISSION_PLUS_LINUX, PERMISSION_PLUS_HOST_API_OPEN_SETTINGS_RESPONSE, GObject)

struct _permission_plus_linuxPermissionPlusHostApiOpenSettingsResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(permission_plus_linuxPermissionPlusHostApiOpenSettingsResponse, permission_plus_linux_permission_plus_host_api_open_settings_response, G_TYPE_OBJECT)

static void permission_plus_linux_permission_plus_host_api_open_settings_response_dispose(GObject* object) {
  permission_plus_linuxPermissionPlusHostApiOpenSettingsResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_OPEN_SETTINGS_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(permission_plus_linux_permission_plus_host_api_open_settings_response_parent_class)->dispose(object);
}

static void permission_plus_linux_permission_plus_host_api_open_settings_response_init(permission_plus_linuxPermissionPlusHostApiOpenSettingsResponse* self) {
}

static void permission_plus_linux_permission_plus_host_api_open_settings_response_class_init(permission_plus_linuxPermissionPlusHostApiOpenSettingsResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = permission_plus_linux_permission_plus_host_api_open_settings_response_dispose;
}

static permission_plus_linuxPermissionPlusHostApiOpenSettingsResponse* permission_plus_linux_permission_plus_host_api_open_settings_response_new(gboolean return_value) {
  permission_plus_linuxPermissionPlusHostApiOpenSettingsResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_OPEN_SETTINGS_RESPONSE(g_object_new(permission_plus_linux_permission_plus_host_api_open_settings_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_bool(return_value));
  return self;
}

static permission_plus_linuxPermissionPlusHostApiOpenSettingsResponse* permission_plus_linux_permission_plus_host_api_open_settings_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  permission_plus_linuxPermissionPlusHostApiOpenSettingsResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_OPEN_SETTINGS_RESPONSE(g_object_new(permission_plus_linux_permission_plus_host_api_open_settings_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

G_DECLARE_FINAL_TYPE(permission_plus_linuxPermissionPlusHostApiShouldShowRationaleResponse, permission_plus_linux_permission_plus_host_api_should_show_rationale_response, PERMISSION_PLUS_LINUX, PERMISSION_PLUS_HOST_API_SHOULD_SHOW_RATIONALE_RESPONSE, GObject)

struct _permission_plus_linuxPermissionPlusHostApiShouldShowRationaleResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(permission_plus_linuxPermissionPlusHostApiShouldShowRationaleResponse, permission_plus_linux_permission_plus_host_api_should_show_rationale_response, G_TYPE_OBJECT)

static void permission_plus_linux_permission_plus_host_api_should_show_rationale_response_dispose(GObject* object) {
  permission_plus_linuxPermissionPlusHostApiShouldShowRationaleResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_SHOULD_SHOW_RATIONALE_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(permission_plus_linux_permission_plus_host_api_should_show_rationale_response_parent_class)->dispose(object);
}

static void permission_plus_linux_permission_plus_host_api_should_show_rationale_response_init(permission_plus_linuxPermissionPlusHostApiShouldShowRationaleResponse* self) {
}

static void permission_plus_linux_permission_plus_host_api_should_show_rationale_response_class_init(permission_plus_linuxPermissionPlusHostApiShouldShowRationaleResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = permission_plus_linux_permission_plus_host_api_should_show_rationale_response_dispose;
}

static permission_plus_linuxPermissionPlusHostApiShouldShowRationaleResponse* permission_plus_linux_permission_plus_host_api_should_show_rationale_response_new(gboolean return_value) {
  permission_plus_linuxPermissionPlusHostApiShouldShowRationaleResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_SHOULD_SHOW_RATIONALE_RESPONSE(g_object_new(permission_plus_linux_permission_plus_host_api_should_show_rationale_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_bool(return_value));
  return self;
}

static permission_plus_linuxPermissionPlusHostApiShouldShowRationaleResponse* permission_plus_linux_permission_plus_host_api_should_show_rationale_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  permission_plus_linuxPermissionPlusHostApiShouldShowRationaleResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_SHOULD_SHOW_RATIONALE_RESPONSE(g_object_new(permission_plus_linux_permission_plus_host_api_should_show_rationale_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

G_DECLARE_FINAL_TYPE(permission_plus_linuxPermissionPlusHostApiGetLocationAccuracyResponse, permission_plus_linux_permission_plus_host_api_get_location_accuracy_response, PERMISSION_PLUS_LINUX, PERMISSION_PLUS_HOST_API_GET_LOCATION_ACCURACY_RESPONSE, GObject)

struct _permission_plus_linuxPermissionPlusHostApiGetLocationAccuracyResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(permission_plus_linuxPermissionPlusHostApiGetLocationAccuracyResponse, permission_plus_linux_permission_plus_host_api_get_location_accuracy_response, G_TYPE_OBJECT)

static void permission_plus_linux_permission_plus_host_api_get_location_accuracy_response_dispose(GObject* object) {
  permission_plus_linuxPermissionPlusHostApiGetLocationAccuracyResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_GET_LOCATION_ACCURACY_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(permission_plus_linux_permission_plus_host_api_get_location_accuracy_response_parent_class)->dispose(object);
}

static void permission_plus_linux_permission_plus_host_api_get_location_accuracy_response_init(permission_plus_linuxPermissionPlusHostApiGetLocationAccuracyResponse* self) {
}

static void permission_plus_linux_permission_plus_host_api_get_location_accuracy_response_class_init(permission_plus_linuxPermissionPlusHostApiGetLocationAccuracyResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = permission_plus_linux_permission_plus_host_api_get_location_accuracy_response_dispose;
}

static permission_plus_linuxPermissionPlusHostApiGetLocationAccuracyResponse* permission_plus_linux_permission_plus_host_api_get_location_accuracy_response_new(permission_plus_linuxLocationAccuracyMessage return_value) {
  permission_plus_linuxPermissionPlusHostApiGetLocationAccuracyResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_GET_LOCATION_ACCURACY_RESPONSE(g_object_new(permission_plus_linux_permission_plus_host_api_get_location_accuracy_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_custom(permission_plus_linux_location_accuracy_message_type_id, fl_value_new_int(return_value), (GDestroyNotify)fl_value_unref));
  return self;
}

static permission_plus_linuxPermissionPlusHostApiGetLocationAccuracyResponse* permission_plus_linux_permission_plus_host_api_get_location_accuracy_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  permission_plus_linuxPermissionPlusHostApiGetLocationAccuracyResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_GET_LOCATION_ACCURACY_RESPONSE(g_object_new(permission_plus_linux_permission_plus_host_api_get_location_accuracy_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

G_DECLARE_FINAL_TYPE(permission_plus_linuxPermissionPlusHostApiRequestTemporaryPreciseLocationResponse, permission_plus_linux_permission_plus_host_api_request_temporary_precise_location_response, PERMISSION_PLUS_LINUX, PERMISSION_PLUS_HOST_API_REQUEST_TEMPORARY_PRECISE_LOCATION_RESPONSE, GObject)

struct _permission_plus_linuxPermissionPlusHostApiRequestTemporaryPreciseLocationResponse {
  GObject parent_instance;

  FlValue* value;
};

G_DEFINE_TYPE(permission_plus_linuxPermissionPlusHostApiRequestTemporaryPreciseLocationResponse, permission_plus_linux_permission_plus_host_api_request_temporary_precise_location_response, G_TYPE_OBJECT)

static void permission_plus_linux_permission_plus_host_api_request_temporary_precise_location_response_dispose(GObject* object) {
  permission_plus_linuxPermissionPlusHostApiRequestTemporaryPreciseLocationResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_REQUEST_TEMPORARY_PRECISE_LOCATION_RESPONSE(object);
  g_clear_pointer(&self->value, fl_value_unref);
  G_OBJECT_CLASS(permission_plus_linux_permission_plus_host_api_request_temporary_precise_location_response_parent_class)->dispose(object);
}

static void permission_plus_linux_permission_plus_host_api_request_temporary_precise_location_response_init(permission_plus_linuxPermissionPlusHostApiRequestTemporaryPreciseLocationResponse* self) {
}

static void permission_plus_linux_permission_plus_host_api_request_temporary_precise_location_response_class_init(permission_plus_linuxPermissionPlusHostApiRequestTemporaryPreciseLocationResponseClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = permission_plus_linux_permission_plus_host_api_request_temporary_precise_location_response_dispose;
}

static permission_plus_linuxPermissionPlusHostApiRequestTemporaryPreciseLocationResponse* permission_plus_linux_permission_plus_host_api_request_temporary_precise_location_response_new(permission_plus_linuxPermissionStatusMessage return_value) {
  permission_plus_linuxPermissionPlusHostApiRequestTemporaryPreciseLocationResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_REQUEST_TEMPORARY_PRECISE_LOCATION_RESPONSE(g_object_new(permission_plus_linux_permission_plus_host_api_request_temporary_precise_location_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_custom(permission_plus_linux_permission_status_message_type_id, fl_value_new_int(return_value), (GDestroyNotify)fl_value_unref));
  return self;
}

static permission_plus_linuxPermissionPlusHostApiRequestTemporaryPreciseLocationResponse* permission_plus_linux_permission_plus_host_api_request_temporary_precise_location_response_new_error(const gchar* code, const gchar* message, FlValue* details) {
  permission_plus_linuxPermissionPlusHostApiRequestTemporaryPreciseLocationResponse* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API_REQUEST_TEMPORARY_PRECISE_LOCATION_RESPONSE(g_object_new(permission_plus_linux_permission_plus_host_api_request_temporary_precise_location_response_get_type(), nullptr));
  self->value = fl_value_new_list();
  fl_value_append_take(self->value, fl_value_new_string(code));
  fl_value_append_take(self->value, fl_value_new_string(message != nullptr ? message : ""));
  fl_value_append_take(self->value, details != nullptr ? fl_value_ref(details) : fl_value_new_null());
  return self;
}

struct _permission_plus_linuxPermissionPlusHostApi {
  GObject parent_instance;

  const permission_plus_linuxPermissionPlusHostApiVTable* vtable;
  gpointer user_data;
  GDestroyNotify user_data_free_func;
};

G_DEFINE_TYPE(permission_plus_linuxPermissionPlusHostApi, permission_plus_linux_permission_plus_host_api, G_TYPE_OBJECT)

static void permission_plus_linux_permission_plus_host_api_dispose(GObject* object) {
  permission_plus_linuxPermissionPlusHostApi* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API(object);
  if (self->user_data != nullptr) {
    self->user_data_free_func(self->user_data);
  }
  self->user_data = nullptr;
  G_OBJECT_CLASS(permission_plus_linux_permission_plus_host_api_parent_class)->dispose(object);
}

static void permission_plus_linux_permission_plus_host_api_init(permission_plus_linuxPermissionPlusHostApi* self) {
}

static void permission_plus_linux_permission_plus_host_api_class_init(permission_plus_linuxPermissionPlusHostApiClass* klass) {
  G_OBJECT_CLASS(klass)->dispose = permission_plus_linux_permission_plus_host_api_dispose;
}

static permission_plus_linuxPermissionPlusHostApi* permission_plus_linux_permission_plus_host_api_new(const permission_plus_linuxPermissionPlusHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  permission_plus_linuxPermissionPlusHostApi* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API(g_object_new(permission_plus_linux_permission_plus_host_api_get_type(), nullptr));
  self->vtable = vtable;
  self->user_data = user_data;
  self->user_data_free_func = user_data_free_func;
  return self;
}

static void permission_plus_linux_permission_plus_host_api_check_permission_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  permission_plus_linuxPermissionPlusHostApi* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->check_permission == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  permission_plus_linuxPermissionTypeMessage permission = static_cast<permission_plus_linuxPermissionTypeMessage>(fl_value_get_int(reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value0)))));
  g_autoptr(permission_plus_linuxPermissionPlusHostApiResponseHandle) handle = permission_plus_linux_permission_plus_host_api_response_handle_new(channel, response_handle);
  self->vtable->check_permission(permission, handle, self->user_data);
}

static void permission_plus_linux_permission_plus_host_api_request_permission_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  permission_plus_linuxPermissionPlusHostApi* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->request_permission == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  permission_plus_linuxPermissionTypeMessage permission = static_cast<permission_plus_linuxPermissionTypeMessage>(fl_value_get_int(reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value0)))));
  g_autoptr(permission_plus_linuxPermissionPlusHostApiResponseHandle) handle = permission_plus_linux_permission_plus_host_api_response_handle_new(channel, response_handle);
  self->vtable->request_permission(permission, handle, self->user_data);
}

static void permission_plus_linux_permission_plus_host_api_request_permissions_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  permission_plus_linuxPermissionPlusHostApi* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->request_permissions == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  FlValue* permissions = value0;
  g_autoptr(permission_plus_linuxPermissionPlusHostApiResponseHandle) handle = permission_plus_linux_permission_plus_host_api_response_handle_new(channel, response_handle);
  self->vtable->request_permissions(permissions, handle, self->user_data);
}

static void permission_plus_linux_permission_plus_host_api_open_settings_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  permission_plus_linuxPermissionPlusHostApi* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->open_settings == nullptr) {
    return;
  }

  g_autoptr(permission_plus_linuxPermissionPlusHostApiResponseHandle) handle = permission_plus_linux_permission_plus_host_api_response_handle_new(channel, response_handle);
  self->vtable->open_settings(handle, self->user_data);
}

static void permission_plus_linux_permission_plus_host_api_should_show_rationale_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  permission_plus_linuxPermissionPlusHostApi* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->should_show_rationale == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  permission_plus_linuxPermissionTypeMessage permission = static_cast<permission_plus_linuxPermissionTypeMessage>(fl_value_get_int(reinterpret_cast<FlValue*>(const_cast<gpointer>(fl_value_get_custom_value(value0)))));
  g_autoptr(permission_plus_linuxPermissionPlusHostApiResponseHandle) handle = permission_plus_linux_permission_plus_host_api_response_handle_new(channel, response_handle);
  self->vtable->should_show_rationale(permission, handle, self->user_data);
}

static void permission_plus_linux_permission_plus_host_api_get_location_accuracy_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  permission_plus_linuxPermissionPlusHostApi* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->get_location_accuracy == nullptr) {
    return;
  }

  g_autoptr(permission_plus_linuxPermissionPlusHostApiResponseHandle) handle = permission_plus_linux_permission_plus_host_api_response_handle_new(channel, response_handle);
  self->vtable->get_location_accuracy(handle, self->user_data);
}

static void permission_plus_linux_permission_plus_host_api_request_temporary_precise_location_cb(FlBasicMessageChannel* channel, FlValue* message_, FlBasicMessageChannelResponseHandle* response_handle, gpointer user_data) {
  permission_plus_linuxPermissionPlusHostApi* self = PERMISSION_PLUS_LINUX_PERMISSION_PLUS_HOST_API(user_data);

  if (self->vtable == nullptr || self->vtable->request_temporary_precise_location == nullptr) {
    return;
  }

  FlValue* value0 = fl_value_get_list_value(message_, 0);
  const gchar* purpose_key = fl_value_get_string(value0);
  g_autoptr(permission_plus_linuxPermissionPlusHostApiResponseHandle) handle = permission_plus_linux_permission_plus_host_api_response_handle_new(channel, response_handle);
  self->vtable->request_temporary_precise_location(purpose_key, handle, self->user_data);
}

void permission_plus_linux_permission_plus_host_api_set_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix, const permission_plus_linuxPermissionPlusHostApiVTable* vtable, gpointer user_data, GDestroyNotify user_data_free_func) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");
  g_autoptr(permission_plus_linuxPermissionPlusHostApi) api_data = permission_plus_linux_permission_plus_host_api_new(vtable, user_data, user_data_free_func);

  g_autoptr(permission_plus_linuxMessageCodec) codec = permission_plus_linux_message_codec_new();
  g_autofree gchar* check_permission_channel_name = g_strdup_printf("dev.flutter.pigeon.permission_plus_linux.PermissionPlusHostApi.checkPermission%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) check_permission_channel = fl_basic_message_channel_new(messenger, check_permission_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(check_permission_channel, permission_plus_linux_permission_plus_host_api_check_permission_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* request_permission_channel_name = g_strdup_printf("dev.flutter.pigeon.permission_plus_linux.PermissionPlusHostApi.requestPermission%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) request_permission_channel = fl_basic_message_channel_new(messenger, request_permission_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(request_permission_channel, permission_plus_linux_permission_plus_host_api_request_permission_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* request_permissions_channel_name = g_strdup_printf("dev.flutter.pigeon.permission_plus_linux.PermissionPlusHostApi.requestPermissions%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) request_permissions_channel = fl_basic_message_channel_new(messenger, request_permissions_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(request_permissions_channel, permission_plus_linux_permission_plus_host_api_request_permissions_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* open_settings_channel_name = g_strdup_printf("dev.flutter.pigeon.permission_plus_linux.PermissionPlusHostApi.openSettings%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) open_settings_channel = fl_basic_message_channel_new(messenger, open_settings_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(open_settings_channel, permission_plus_linux_permission_plus_host_api_open_settings_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* should_show_rationale_channel_name = g_strdup_printf("dev.flutter.pigeon.permission_plus_linux.PermissionPlusHostApi.shouldShowRationale%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) should_show_rationale_channel = fl_basic_message_channel_new(messenger, should_show_rationale_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(should_show_rationale_channel, permission_plus_linux_permission_plus_host_api_should_show_rationale_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* get_location_accuracy_channel_name = g_strdup_printf("dev.flutter.pigeon.permission_plus_linux.PermissionPlusHostApi.getLocationAccuracy%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) get_location_accuracy_channel = fl_basic_message_channel_new(messenger, get_location_accuracy_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(get_location_accuracy_channel, permission_plus_linux_permission_plus_host_api_get_location_accuracy_cb, g_object_ref(api_data), g_object_unref);
  g_autofree gchar* request_temporary_precise_location_channel_name = g_strdup_printf("dev.flutter.pigeon.permission_plus_linux.PermissionPlusHostApi.requestTemporaryPreciseLocation%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) request_temporary_precise_location_channel = fl_basic_message_channel_new(messenger, request_temporary_precise_location_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(request_temporary_precise_location_channel, permission_plus_linux_permission_plus_host_api_request_temporary_precise_location_cb, g_object_ref(api_data), g_object_unref);
}

void permission_plus_linux_permission_plus_host_api_clear_method_handlers(FlBinaryMessenger* messenger, const gchar* suffix) {
  g_autofree gchar* dot_suffix = suffix != nullptr ? g_strdup_printf(".%s", suffix) : g_strdup("");

  g_autoptr(permission_plus_linuxMessageCodec) codec = permission_plus_linux_message_codec_new();
  g_autofree gchar* check_permission_channel_name = g_strdup_printf("dev.flutter.pigeon.permission_plus_linux.PermissionPlusHostApi.checkPermission%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) check_permission_channel = fl_basic_message_channel_new(messenger, check_permission_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(check_permission_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* request_permission_channel_name = g_strdup_printf("dev.flutter.pigeon.permission_plus_linux.PermissionPlusHostApi.requestPermission%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) request_permission_channel = fl_basic_message_channel_new(messenger, request_permission_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(request_permission_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* request_permissions_channel_name = g_strdup_printf("dev.flutter.pigeon.permission_plus_linux.PermissionPlusHostApi.requestPermissions%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) request_permissions_channel = fl_basic_message_channel_new(messenger, request_permissions_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(request_permissions_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* open_settings_channel_name = g_strdup_printf("dev.flutter.pigeon.permission_plus_linux.PermissionPlusHostApi.openSettings%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) open_settings_channel = fl_basic_message_channel_new(messenger, open_settings_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(open_settings_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* should_show_rationale_channel_name = g_strdup_printf("dev.flutter.pigeon.permission_plus_linux.PermissionPlusHostApi.shouldShowRationale%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) should_show_rationale_channel = fl_basic_message_channel_new(messenger, should_show_rationale_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(should_show_rationale_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* get_location_accuracy_channel_name = g_strdup_printf("dev.flutter.pigeon.permission_plus_linux.PermissionPlusHostApi.getLocationAccuracy%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) get_location_accuracy_channel = fl_basic_message_channel_new(messenger, get_location_accuracy_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(get_location_accuracy_channel, nullptr, nullptr, nullptr);
  g_autofree gchar* request_temporary_precise_location_channel_name = g_strdup_printf("dev.flutter.pigeon.permission_plus_linux.PermissionPlusHostApi.requestTemporaryPreciseLocation%s", dot_suffix);
  g_autoptr(FlBasicMessageChannel) request_temporary_precise_location_channel = fl_basic_message_channel_new(messenger, request_temporary_precise_location_channel_name, FL_MESSAGE_CODEC(codec));
  fl_basic_message_channel_set_message_handler(request_temporary_precise_location_channel, nullptr, nullptr, nullptr);
}

void permission_plus_linux_permission_plus_host_api_respond_check_permission(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, permission_plus_linuxPermissionStatusMessage return_value) {
  g_autoptr(permission_plus_linuxPermissionPlusHostApiCheckPermissionResponse) response = permission_plus_linux_permission_plus_host_api_check_permission_response_new(return_value);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "PermissionPlusHostApi", "checkPermission", error->message);
  }
}

void permission_plus_linux_permission_plus_host_api_respond_error_check_permission(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(permission_plus_linuxPermissionPlusHostApiCheckPermissionResponse) response = permission_plus_linux_permission_plus_host_api_check_permission_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "PermissionPlusHostApi", "checkPermission", error->message);
  }
}

void permission_plus_linux_permission_plus_host_api_respond_request_permission(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, permission_plus_linuxPermissionStatusMessage return_value) {
  g_autoptr(permission_plus_linuxPermissionPlusHostApiRequestPermissionResponse) response = permission_plus_linux_permission_plus_host_api_request_permission_response_new(return_value);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "PermissionPlusHostApi", "requestPermission", error->message);
  }
}

void permission_plus_linux_permission_plus_host_api_respond_error_request_permission(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(permission_plus_linuxPermissionPlusHostApiRequestPermissionResponse) response = permission_plus_linux_permission_plus_host_api_request_permission_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "PermissionPlusHostApi", "requestPermission", error->message);
  }
}

void permission_plus_linux_permission_plus_host_api_respond_request_permissions(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, FlValue* return_value) {
  g_autoptr(permission_plus_linuxPermissionPlusHostApiRequestPermissionsResponse) response = permission_plus_linux_permission_plus_host_api_request_permissions_response_new(return_value);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "PermissionPlusHostApi", "requestPermissions", error->message);
  }
}

void permission_plus_linux_permission_plus_host_api_respond_error_request_permissions(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(permission_plus_linuxPermissionPlusHostApiRequestPermissionsResponse) response = permission_plus_linux_permission_plus_host_api_request_permissions_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "PermissionPlusHostApi", "requestPermissions", error->message);
  }
}

void permission_plus_linux_permission_plus_host_api_respond_open_settings(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, gboolean return_value) {
  g_autoptr(permission_plus_linuxPermissionPlusHostApiOpenSettingsResponse) response = permission_plus_linux_permission_plus_host_api_open_settings_response_new(return_value);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "PermissionPlusHostApi", "openSettings", error->message);
  }
}

void permission_plus_linux_permission_plus_host_api_respond_error_open_settings(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(permission_plus_linuxPermissionPlusHostApiOpenSettingsResponse) response = permission_plus_linux_permission_plus_host_api_open_settings_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "PermissionPlusHostApi", "openSettings", error->message);
  }
}

void permission_plus_linux_permission_plus_host_api_respond_should_show_rationale(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, gboolean return_value) {
  g_autoptr(permission_plus_linuxPermissionPlusHostApiShouldShowRationaleResponse) response = permission_plus_linux_permission_plus_host_api_should_show_rationale_response_new(return_value);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "PermissionPlusHostApi", "shouldShowRationale", error->message);
  }
}

void permission_plus_linux_permission_plus_host_api_respond_error_should_show_rationale(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(permission_plus_linuxPermissionPlusHostApiShouldShowRationaleResponse) response = permission_plus_linux_permission_plus_host_api_should_show_rationale_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "PermissionPlusHostApi", "shouldShowRationale", error->message);
  }
}

void permission_plus_linux_permission_plus_host_api_respond_get_location_accuracy(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, permission_plus_linuxLocationAccuracyMessage return_value) {
  g_autoptr(permission_plus_linuxPermissionPlusHostApiGetLocationAccuracyResponse) response = permission_plus_linux_permission_plus_host_api_get_location_accuracy_response_new(return_value);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "PermissionPlusHostApi", "getLocationAccuracy", error->message);
  }
}

void permission_plus_linux_permission_plus_host_api_respond_error_get_location_accuracy(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(permission_plus_linuxPermissionPlusHostApiGetLocationAccuracyResponse) response = permission_plus_linux_permission_plus_host_api_get_location_accuracy_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "PermissionPlusHostApi", "getLocationAccuracy", error->message);
  }
}

void permission_plus_linux_permission_plus_host_api_respond_request_temporary_precise_location(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, permission_plus_linuxPermissionStatusMessage return_value) {
  g_autoptr(permission_plus_linuxPermissionPlusHostApiRequestTemporaryPreciseLocationResponse) response = permission_plus_linux_permission_plus_host_api_request_temporary_precise_location_response_new(return_value);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "PermissionPlusHostApi", "requestTemporaryPreciseLocation", error->message);
  }
}

void permission_plus_linux_permission_plus_host_api_respond_error_request_temporary_precise_location(permission_plus_linuxPermissionPlusHostApiResponseHandle* response_handle, const gchar* code, const gchar* message, FlValue* details) {
  g_autoptr(permission_plus_linuxPermissionPlusHostApiRequestTemporaryPreciseLocationResponse) response = permission_plus_linux_permission_plus_host_api_request_temporary_precise_location_response_new_error(code, message, details);
  g_autoptr(GError) error = nullptr;
  if (!fl_basic_message_channel_respond(response_handle->channel, response_handle->response_handle, response->value, &error)) {
    g_warning("Failed to send response to %s.%s: %s", "PermissionPlusHostApi", "requestTemporaryPreciseLocation", error->message);
  }
}
